# docker-compose.yml
version: "3.9"

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Sempre lemos o .env "base" + o específico
    env_file:
      - .env
      - .env.${ENV:-dev}
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"           # opcional em dev
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  postgres_data:
