[tool.poetry]
name = "fasttrackapi-projeto-prisma"
version = "0.1.0"
description = ""
authors = ["Seu Nome <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = { extras = ["standard"], version = "^0.27.0" }
sqlalchemy = "^2.0"
alembic = "^1.13.0"
pydantic = "^2.0"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
