global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["host.docker.internal:8000"]

# ⚠️ Se estiver rodando a FastAPI também em container, ajuste `host.docker.internal` para o nome do serviço no `docker-compose`.