"""create all tables

Revision ID: 0f309be50b5e
Revises: 
Create Date: 2025-06-20 11:18:22.132066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f309be50b5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_datetime', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('weather_main', sa.String(), nullable=False),
    sa.Column('weather_desc', sa.String(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_infos_id'), 'forecast_infos', ['id'], unique=False)
    op.create_table('local_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('venue_type', sa.Enum('AUDITORIO', 'SALAO', name='venuetypes'), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('manually_edited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_infos_id'), 'local_infos', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('local_info_id', sa.Integer(), nullable=True),
    sa.Column('forecast_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_info_id'], ['forecast_infos.id'], ),
    sa.ForeignKeyConstraint(['local_info_id'], ['local_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_local_infos_id'), table_name='local_infos')
    op.drop_table('local_infos')
    op.drop_index(op.f('ix_forecast_infos_id'), table_name='forecast_infos')
    op.drop_table('forecast_infos')
    # ### end Alembic commands ###
